services:
  mysql:
    image: mysql:8.4
    container_name: ai-task-manager-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ai_task_manager
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-task-manager-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ai_task_manager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

      SPRING_AI_OPENAI_BASE_URL: https://openrouter.ai/api
      SPRING_AI_OPENAI_API_KEY: ${SPRING_AI_OPENAI_API_KEY}

    depends_on:
      - mysql

volumes:
  mysql_data:
